# Makefile -- Build PageMapTools, assuming GNU toolchain. # Copyright C2009 by EQware Engineering, Inc. # # Makefile is part of PageMapTools. # # PageMapTools is free software: you can redistribute it and/or modify # it under the terms of version 3 of the GNU General Public License # as published by the Free Software Foundation # # PageMapTools is distributed in the hope that it will be useful, # but WITHOUT ANY WARRANTY; without even the implied warranty of # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the # GNU General Public License for more details. # # You should have received a copy of the GNU General Public License # along with PageMapTools. If not, see http://www.gnu.or/licenses. # 


all: page-collect page-analyze 
page-collect: page-collect.c 
page-analyze: page-analyze.cpp 
clean: 
	rm page-collect page-analyze
